version: "3.9"
services:
  postgres-test:
    image: postgres:16
    environment:
      POSTGRES_TEST_USER: crucial
      POSTGRES_TEST_PASSWORD: j
      POSTGRES_TEST_DB: restapi_test
    ports:
      - "5433:5433"
  postgres-dev:
    image: postgres:16
    environment:
      POSTGRES_USER: crucial
      POSTGRES_PASSWORD: j
      POSTGRES_DB: restapi_dev
    ports:
      - "5432:5432"