version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: crucial
      POSTGRES_PASSWORD: j
      POSTGRES_DB: restapi_dev
    ports:
      - "5432:5432"